
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.blocks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.blocks.item.WiresitemItem;
import net.mcreator.blocks.item.SecretdataItem;
import net.mcreator.blocks.item.ScrapItem;
import net.mcreator.blocks.item.ScannerseekerItem;
import net.mcreator.blocks.item.ScannerItem;
import net.mcreator.blocks.item.PlanksitemItem;
import net.mcreator.blocks.item.PillsItem;
import net.mcreator.blocks.item.LvlArmorItem;
import net.mcreator.blocks.item.KeysItem;
import net.mcreator.blocks.item.FusebrokenItem;
import net.mcreator.blocks.item.FuseItem;
import net.mcreator.blocks.item.FullusbItem;
import net.mcreator.blocks.item.EnfullusbItem;
import net.mcreator.blocks.item.CrowbarItem;
import net.mcreator.blocks.item.ClothitemItem;
import net.mcreator.blocks.item.CircuitboardItem;
import net.mcreator.blocks.item.Armor3ArmorItem;
import net.mcreator.blocks.item.Armor2ArmorItem;
import net.mcreator.blocks.item.Armor1ArmorItem;
import net.mcreator.blocks.item.AcidItem;
import net.mcreator.blocks.QzMod;

public class QzModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, QzMod.MODID);
	public static final RegistryObject<Item> METAL_1 = block(QzModBlocks.METAL_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_2 = block(QzModBlocks.METAL_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_3 = block(QzModBlocks.METAL_3, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_4 = block(QzModBlocks.METAL_4, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_5 = block(QzModBlocks.METAL_5, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> ZONE = block(QzModBlocks.ZONE, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> TUBESBLOCK = block(QzModBlocks.TUBESBLOCK, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_01 = block(QzModBlocks.METAL_01, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METALINSNOW = block(QzModBlocks.METALINSNOW, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METAL_2INSNOW = block(QzModBlocks.METAL_2INSNOW, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WARN = block(QzModBlocks.WARN, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> SCIFIBLOCK = block(QzModBlocks.SCIFIBLOCK, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> LOGBLOCKMAIN = block(QzModBlocks.LOGBLOCKMAIN, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> PLANKS_1 = block(QzModBlocks.PLANKS_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> PLANKS_2 = block(QzModBlocks.PLANKS_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> PLANKS_3 = block(QzModBlocks.PLANKS_3, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> PLANKS_4 = block(QzModBlocks.PLANKS_4, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLUE = block(QzModBlocks.BLUE, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> YELLOW = block(QzModBlocks.YELLOW, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WALL_1 = block(QzModBlocks.WALL_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WALL_2 = block(QzModBlocks.WALL_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WALL_3 = block(QzModBlocks.WALL_3, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> FLOOR_1 = block(QzModBlocks.FLOOR_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WALL_4 = block(QzModBlocks.WALL_4, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CONCRETTEWALL = block(QzModBlocks.CONCRETTEWALL, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> RSPAWN = block(QzModBlocks.RSPAWN, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> PLANK_1 = block(QzModBlocks.PLANK_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> LOG = block(QzModBlocks.LOG, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WOODLOGWITHSNOW = block(QzModBlocks.WOODLOGWITHSNOW, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASS_1 = block(QzModBlocks.GLASS_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASS_2 = block(QzModBlocks.GLASS_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> ICEDEATH = block(QzModBlocks.ICEDEATH, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WOODSTAIRS = block(QzModBlocks.WOODSTAIRS, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> ROOFSLOPE_1 = block(QzModBlocks.ROOFSLOPE_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> ROOFCORNER_1 = block(QzModBlocks.ROOFCORNER_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> ROOFCORNER_2 = block(QzModBlocks.ROOFCORNER_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> TUBES = block(QzModBlocks.TUBES, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> TUBESCORNER = block(QzModBlocks.TUBESCORNER, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CONCRETTEWALL_1 = block(QzModBlocks.CONCRETTEWALL_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CONCRETTEWALL_2 = block(QzModBlocks.CONCRETTEWALL_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CONCRETTEWALL_3 = block(QzModBlocks.CONCRETTEWALL_3, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CONCRETTEWALL_04 = block(QzModBlocks.CONCRETTEWALL_04, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> CHAINLINK = block(QzModBlocks.CHAINLINK, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASSPURLE = block(QzModBlocks.GLASSPURLE, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASSORANGE = block(QzModBlocks.GLASSORANGE, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASSBLACK = block(QzModBlocks.GLASSBLACK, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASSGRAY = block(QzModBlocks.GLASSGRAY, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> GLASSINARK = block(QzModBlocks.GLASSINARK, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> METALSTAIR = block(QzModBlocks.METALSTAIR, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WOODSTAIR = block(QzModBlocks.WOODSTAIR, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> TILESTAIR = block(QzModBlocks.TILESTAIR, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> WPNBOX = block(QzModBlocks.WPNBOX, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> VENT = block(QzModBlocks.VENT, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_1 = block(QzModBlocks.BLOCK_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_2 = block(QzModBlocks.BLOCK_2, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_3 = block(QzModBlocks.BLOCK_3, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_4 = block(QzModBlocks.BLOCK_4, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_5 = block(QzModBlocks.BLOCK_5, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_6 = block(QzModBlocks.BLOCK_6, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_7 = block(QzModBlocks.BLOCK_7, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_8 = block(QzModBlocks.BLOCK_8, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_9 = block(QzModBlocks.BLOCK_9, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_10 = block(QzModBlocks.BLOCK_10, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_11 = block(QzModBlocks.BLOCK_11, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_12 = block(QzModBlocks.BLOCK_12, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_13 = block(QzModBlocks.BLOCK_13, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_14 = block(QzModBlocks.BLOCK_14, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_15 = block(QzModBlocks.BLOCK_15, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_16 = block(QzModBlocks.BLOCK_16, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_17 = block(QzModBlocks.BLOCK_17, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_18 = block(QzModBlocks.BLOCK_18, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_19 = block(QzModBlocks.BLOCK_19, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_20 = block(QzModBlocks.BLOCK_20, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_21 = block(QzModBlocks.BLOCK_21, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_22 = block(QzModBlocks.BLOCK_22, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_23 = block(QzModBlocks.BLOCK_23, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_24 = block(QzModBlocks.BLOCK_24, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_25 = block(QzModBlocks.BLOCK_25, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_26 = block(QzModBlocks.BLOCK_26, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_27 = block(QzModBlocks.BLOCK_27, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_28 = block(QzModBlocks.BLOCK_28, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_29 = block(QzModBlocks.BLOCK_29, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_30 = block(QzModBlocks.BLOCK_30, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_31 = block(QzModBlocks.BLOCK_31, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_38 = block(QzModBlocks.BLOCK_38, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_39 = block(QzModBlocks.BLOCK_39, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_40 = block(QzModBlocks.BLOCK_40, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_41 = block(QzModBlocks.BLOCK_41, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> TILE_1 = block(QzModBlocks.TILE_1, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_42 = block(QzModBlocks.BLOCK_42, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_43 = block(QzModBlocks.BLOCK_43, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_44 = block(QzModBlocks.BLOCK_44, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_45 = block(QzModBlocks.BLOCK_45, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_46 = block(QzModBlocks.BLOCK_46, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_47 = block(QzModBlocks.BLOCK_47, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> BLOCK_48 = block(QzModBlocks.BLOCK_48, QzModTabs.TAB_BLOCKS);
	public static final RegistryObject<Item> VENTOPENED = block(QzModBlocks.VENTOPENED, null);
	public static final RegistryObject<Item> SUPPLY = block(QzModBlocks.SUPPLY, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> SUPPLYINSNOW = block(QzModBlocks.SUPPLYINSNOW, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> PC = block(QzModBlocks.PC, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> EJECTOR = block(QzModBlocks.EJECTOR, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> DESTROYEDDROID = block(QzModBlocks.DESTROYEDDROID, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> CASSETTEPLAYER = block(QzModBlocks.CASSETTEPLAYER, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> STORAGEENCHEST = block(QzModBlocks.STORAGEENCHEST, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> WORKBENCH = block(QzModBlocks.WORKBENCH, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> FUSEBOXCLOSED = block(QzModBlocks.FUSEBOXCLOSED, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> TUMBA = block(QzModBlocks.TUMBA, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> CLOSET = block(QzModBlocks.CLOSET, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> PLANKS = block(QzModBlocks.PLANKS, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> CLOTHBLOCK = block(QzModBlocks.CLOTHBLOCK, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> WIRESBLOCK = block(QzModBlocks.WIRESBLOCK, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> SCRAPBLOCK = block(QzModBlocks.SCRAPBLOCK, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> MEDKIT = block(QzModBlocks.MEDKIT, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> PILLSPLACED = block(QzModBlocks.PILLSPLACED, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> KEYSPLACED = block(QzModBlocks.KEYSPLACED, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> CONSOLE = block(QzModBlocks.CONSOLE, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> MEDKITWALL = block(QzModBlocks.MEDKITWALL, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> BOOKS = block(QzModBlocks.BOOKS, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> VENTCLOSED = block(QzModBlocks.VENTCLOSED, QzModTabs.TAB_INTERACTIVE_BLOCK);
	public static final RegistryObject<Item> DECORATIVECRATE = block(QzModBlocks.DECORATIVECRATE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DECORATIVECRATESNOW = block(QzModBlocks.DECORATIVECRATESNOW, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DOTSANIM = block(QzModBlocks.DOTSANIM, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DISKOBLOCK = block(QzModBlocks.DISKOBLOCK, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DISCOBLOCK_1 = block(QzModBlocks.DISCOBLOCK_1, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DISCOBLOCK_2 = block(QzModBlocks.DISCOBLOCK_2, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> TABLERESOURCESPAWNER = block(QzModBlocks.TABLERESOURCESPAWNER, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> TABBLE = block(QzModBlocks.TABBLE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> SHELF = block(QzModBlocks.SHELF, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> BARREL = block(QzModBlocks.BARREL, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> BARRELGREEN = block(QzModBlocks.BARRELGREEN, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> BIOHAZARDBARREL = block(QzModBlocks.BIOHAZARDBARREL, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> A_RUBBER_DUCK = block(QzModBlocks.A_RUBBER_DUCK, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> TV = block(QzModBlocks.TV, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> TABLELAMP = block(QzModBlocks.TABLELAMP, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> METALGRATE = block(QzModBlocks.METALGRATE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> FENCCE = block(QzModBlocks.FENCCE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> ANTENAGROUND = block(QzModBlocks.ANTENAGROUND, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> ANTENABASE = block(QzModBlocks.ANTENABASE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> ANTENAUP = block(QzModBlocks.ANTENAUP, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> LOGEND = block(QzModBlocks.LOGEND, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> WOODSHELF = block(QzModBlocks.WOODSHELF, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> WOODTABLE = block(QzModBlocks.WOODTABLE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> WOODCHAIR = block(QzModBlocks.WOODCHAIR, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> WOODLOGWITHSNOWEND = block(QzModBlocks.WOODLOGWITHSNOWEND, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> PAPERS = block(QzModBlocks.PAPERS, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> SCIFILAMPOFF = block(QzModBlocks.SCIFILAMPOFF, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> SCIFILAMPON = block(QzModBlocks.SCIFILAMPON, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> DISPLAY_1 = block(QzModBlocks.DISPLAY_1, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> GREENBLINK = block(QzModBlocks.GREENBLINK, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> REDBLINK = block(QzModBlocks.REDBLINK, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> LOCKERDOWN = block(QzModBlocks.LOCKERDOWN, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> CELLLAMP = block(QzModBlocks.CELLLAMP, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> CRATE = block(QzModBlocks.CRATE, QzModTabs.TAB_DECORATION);
	public static final RegistryObject<Item> SCRAP = REGISTRY.register("scrap", () -> new ScrapItem());
	public static final RegistryObject<Item> SECRETDATA = REGISTRY.register("secretdata", () -> new SecretdataItem());
	public static final RegistryObject<Item> FULLUSB = REGISTRY.register("fullusb", () -> new FullusbItem());
	public static final RegistryObject<Item> ENFULLUSB = REGISTRY.register("enfullusb", () -> new EnfullusbItem());
	public static final RegistryObject<Item> CIRCUITBOARD = REGISTRY.register("circuitboard", () -> new CircuitboardItem());
	public static final RegistryObject<Item> DROID_SPAWN_EGG = REGISTRY.register("droid_spawn_egg", () -> new ForgeSpawnEggItem(QzModEntities.DROID, -6750208, -16777063, new Item.Properties().tab(QzModTabs.TAB_BL_ITEMS)));
	public static final RegistryObject<Item> PLANKSITEM = REGISTRY.register("planksitem", () -> new PlanksitemItem());
	public static final RegistryObject<Item> CLOTHITEM = REGISTRY.register("clothitem", () -> new ClothitemItem());
	public static final RegistryObject<Item> WIRESITEM = REGISTRY.register("wiresitem", () -> new WiresitemItem());
	public static final RegistryObject<Item> LVL_ARMOR_CHESTPLATE = REGISTRY.register("lvl_armor_chestplate", () -> new LvlArmorItem.Chestplate());
	public static final RegistryObject<Item> ARMOR_1_ARMOR_CHESTPLATE = REGISTRY.register("armor_1_armor_chestplate", () -> new Armor1ArmorItem.Chestplate());
	public static final RegistryObject<Item> ARMOR_2_ARMOR_CHESTPLATE = REGISTRY.register("armor_2_armor_chestplate", () -> new Armor2ArmorItem.Chestplate());
	public static final RegistryObject<Item> ARMOR_3_ARMOR_CHESTPLATE = REGISTRY.register("armor_3_armor_chestplate", () -> new Armor3ArmorItem.Chestplate());
	public static final RegistryObject<Item> ACID_BUCKET = REGISTRY.register("acid_bucket", () -> new AcidItem());
	public static final RegistryObject<Item> SCANNER = REGISTRY.register("scanner", () -> new ScannerItem());
	public static final RegistryObject<Item> SCANNERSEEKER = REGISTRY.register("scannerseeker", () -> new ScannerseekerItem());
	public static final RegistryObject<Item> CROWBAR = REGISTRY.register("crowbar", () -> new CrowbarItem());
	public static final RegistryObject<Item> FUSE = REGISTRY.register("fuse", () -> new FuseItem());
	public static final RegistryObject<Item> FUSEBROKEN = REGISTRY.register("fusebroken", () -> new FusebrokenItem());
	public static final RegistryObject<Item> PILLS = REGISTRY.register("pills", () -> new PillsItem());
	public static final RegistryObject<Item> KEYS = REGISTRY.register("keys", () -> new KeysItem());
	public static final RegistryObject<Item> DOORBOTTOMCLOSED = block(QzModBlocks.DOORBOTTOMCLOSED, QzModTabs.TAB_DOORS);
	public static final RegistryObject<Item> SAFETYDOORBOTTOMCLOSE = block(QzModBlocks.SAFETYDOORBOTTOMCLOSE, QzModTabs.TAB_DOORS);
	public static final RegistryObject<Item> WOODENDOORBOTOMCLOSED = block(QzModBlocks.WOODENDOORBOTOMCLOSED, QzModTabs.TAB_DOORS);
	public static final RegistryObject<Item> WDBSC = block(QzModBlocks.WDBSC, QzModTabs.TAB_DOORS);
	public static final RegistryObject<Item> LOCKERBIGDOWNCLOSED = block(QzModBlocks.LOCKERBIGDOWNCLOSED, QzModTabs.TAB_DOORS);
	public static final RegistryObject<Item> EJECTORUP = block(QzModBlocks.EJECTORUP, null);
	public static final RegistryObject<Item> PLANK_3 = block(QzModBlocks.PLANK_3, null);
	public static final RegistryObject<Item> PLANK_2 = block(QzModBlocks.PLANK_2, null);
	public static final RegistryObject<Item> PLANK_0 = block(QzModBlocks.PLANK_0, null);
	public static final RegistryObject<Item> TUMBAV_1 = block(QzModBlocks.TUMBAV_1, null);
	public static final RegistryObject<Item> TUMBAV_2 = block(QzModBlocks.TUMBAV_2, null);
	public static final RegistryObject<Item> TUMBAV_3 = block(QzModBlocks.TUMBAV_3, null);
	public static final RegistryObject<Item> TVV_1 = block(QzModBlocks.TVV_1, null);
	public static final RegistryObject<Item> TVV_2 = block(QzModBlocks.TVV_2, null);
	public static final RegistryObject<Item> TABLELAMPLIGHT = block(QzModBlocks.TABLELAMPLIGHT, null);
	public static final RegistryObject<Item> CLOSETV_1 = block(QzModBlocks.CLOSETV_1, null);
	public static final RegistryObject<Item> CLOSETV_2 = block(QzModBlocks.CLOSETV_2, null);
	public static final RegistryObject<Item> FUSEBOXOPENED = block(QzModBlocks.FUSEBOXOPENED, null);
	public static final RegistryObject<Item> FUSEBOXOPENON = block(QzModBlocks.FUSEBOXOPENON, null);
	public static final RegistryObject<Item> DOORBOTTOMOPEN = block(QzModBlocks.DOORBOTTOMOPEN, null);
	public static final RegistryObject<Item> DOORTOPCLOSED = block(QzModBlocks.DOORTOPCLOSED, null);
	public static final RegistryObject<Item> DOORTOPOPENED = block(QzModBlocks.DOORTOPOPENED, null);
	public static final RegistryObject<Item> WOODENDOORBOTOMOPENED = block(QzModBlocks.WOODENDOORBOTOMOPENED, null);
	public static final RegistryObject<Item> WOODENDOORTOPOPENED = block(QzModBlocks.WOODENDOORTOPOPENED, null);
	public static final RegistryObject<Item> WOODENDOORTOPCLOSED = block(QzModBlocks.WOODENDOORTOPCLOSED, null);
	public static final RegistryObject<Item> WDBSO = block(QzModBlocks.WDBSO, null);
	public static final RegistryObject<Item> WDTSC = block(QzModBlocks.WDTSC, null);
	public static final RegistryObject<Item> WDTSO = block(QzModBlocks.WDTSO, null);
	public static final RegistryObject<Item> SAFETYDOORBOTTOMOPEN = block(QzModBlocks.SAFETYDOORBOTTOMOPEN, null);
	public static final RegistryObject<Item> SAFETYDOORTOPCLOSED = block(QzModBlocks.SAFETYDOORTOPCLOSED, null);
	public static final RegistryObject<Item> SAFETYDOORTOPOPENED = block(QzModBlocks.SAFETYDOORTOPOPENED, null);
	public static final RegistryObject<Item> WORKBENCHSLOTS = block(QzModBlocks.WORKBENCHSLOTS, null);
	public static final RegistryObject<Item> LOCKERUP = block(QzModBlocks.LOCKERUP, null);
	public static final RegistryObject<Item> LOCKERBIGUPCLOSED = block(QzModBlocks.LOCKERBIGUPCLOSED, null);
	public static final RegistryObject<Item> LOCKERBIGDOWNOPENED = block(QzModBlocks.LOCKERBIGDOWNOPENED, null);
	public static final RegistryObject<Item> LOCKERBIGUPOPENED = block(QzModBlocks.LOCKERBIGUPOPENED, null);
	public static final RegistryObject<Item> MEDKITWALLEMPTY = block(QzModBlocks.MEDKITWALLEMPTY, null);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
