modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="qz"
version="1.0.0"
displayName="QZ_Blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BiG_LOO"

[[dependencies.qz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




